theme: jekyll-theme-minimal
title: Writing slow regexp is easier than you think (and want it to be)
description: Maciek RzÄ…sa, <a href="https://twitter.com/mjrzasa">@mjrzasa</a>, <a href="https://textmaster.com">TextMaster</a>
